#include "extras-menu.h"
#include "popover.h"
#include "preferences.h"

static void extras_menu_plugin_construct(XfcePanelPlugin *panel_plugin);

/* Registers the plugin with the panel. This macro expands to define
 * extras_menu_plugin_get_type(), extras_menu_plugin_register_type(),
 * and the module entry point xfce_panel_module_init(); it expects us
 * to provide extras_menu_plugin_init() and extras_menu_plugin_class_init()
 * ourselves below (their prototypes are generated by this macro, not
 * their bodies). Do NOT also call G_DEFINE_TYPE here -- that generates
 * the same symbols a second time and fails to compile. */
XFCE_PANEL_DEFINE_PLUGIN(ExtrasMenuPlugin, extras_menu_plugin)

static void
extras_menu_plugin_class_init(ExtrasMenuPluginClass *klass)
{
    XfcePanelPluginClass *plugin_class = XFCE_PANEL_PLUGIN_CLASS(klass);
    plugin_class->construct = extras_menu_plugin_construct;
}

static void
extras_menu_plugin_init(ExtrasMenuPlugin *plugin)
{
    /* Widgets are built in construct(), once the plugin has a panel to
     * attach to; nothing to do here yet. */
    plugin->toggle_button = NULL;
    plugin->button_icon = NULL;
    plugin->popover = NULL;
    plugin->volume_scale = NULL;
    plugin->volume_icon = NULL;
    plugin->audio = NULL;
    plugin->updating_volume_from_backend = FALSE;
    plugin->brightness_scale = NULL;
    plugin->brightness = NULL;
    plugin->updating_brightness_from_backend = FALSE;
    plugin->bluetooth_toggle = NULL;
    plugin->bluetooth = NULL;
    plugin->updating_bluetooth_from_backend = FALSE;
    plugin->bluetooth_last_available = FALSE;
    plugin->bluetooth_last_powered = FALSE;
    plugin->bluetooth_has_state = FALSE;
}

/* Moves the dropdown window so it sits next to the panel button,
 * horizontally centered on it, and on whichever side there's actually
 * room: below the button for a top (or left/right) panel, above the
 * button for a bottom panel. Called every time we're about to show
 * the window, since the button's on-screen position -- and the
 * panel's screen position -- can change (panel moved, screen
 * resolution changed, ...). */
static void
position_dropdown_below_button(ExtrasMenuPlugin *plugin)
{
    GdkWindow *button_window = gtk_widget_get_window(plugin->toggle_button);
    if (button_window == NULL)
        return;

    gint origin_x = 0, origin_y = 0;
    gdk_window_get_origin(button_window, &origin_x, &origin_y);

    GtkAllocation button_alloc;
    gtk_widget_get_allocation(plugin->toggle_button, &button_alloc);

    /* Ask the dropdown for its natural size so we can center it under
     * the button rather than align it to one edge -- this way the
     * dropdown stays centered on the trigger icon regardless of where
     * along the panel the plugin is placed. */
    GtkRequisition natural_size;
    gtk_widget_get_preferred_size(plugin->popover, NULL, &natural_size);

    gint button_center_x = origin_x + button_alloc.x + (button_alloc.width / 2);
    gint x = button_center_x - (natural_size.width / 2);

    /* If the panel sits at the bottom of the screen, there's no room
     * to open downward -- flip and open the dropdown upward instead,
     * so its bottom edge sits just above the button. For a top (or
     * any other) panel position, keep opening downward as before. */
    XfceScreenPosition screen_position =
        xfce_panel_plugin_get_screen_position(XFCE_PANEL_PLUGIN(plugin));

    gint y;
    if (xfce_screen_position_is_bottom(screen_position))
        y = origin_y + button_alloc.y - natural_size.height;
    else
        y = origin_y + button_alloc.y + button_alloc.height;

    /* Keep the dropdown fully on-screen horizontally: centering can
     * push it past either edge for buttons near the left or right end
     * of the panel, so clamp against the monitor's actual bounds
     * rather than just the left edge. */
    GdkDisplay *display = gdk_window_get_display(button_window);
    GdkMonitor *monitor = gdk_display_get_monitor_at_window(display, button_window);
    GdkRectangle monitor_geom;
    gdk_monitor_get_geometry(monitor, &monitor_geom);

    if (x < monitor_geom.x)
        x = monitor_geom.x;
    else if (x + natural_size.width > monitor_geom.x + monitor_geom.width)
        x = monitor_geom.x + monitor_geom.width - natural_size.width;

    gtk_window_move(GTK_WINDOW(plugin->popover), x, y);
}

/* Toggle the dropdown open/closed when the panel button is clicked.
 * Implemented as a plain GtkWindow (see extras-menu.h for why) rather
 * than a GtkPopover, so opening it means: position it under the
 * button, then show it and force it above other windows including the
 * always-on-top panel. */
static void
on_toggle_button_clicked(GtkToggleButton *button, ExtrasMenuPlugin *plugin)
{
    if (gtk_toggle_button_get_active(button))
    {
        position_dropdown_below_button(plugin);
        gtk_window_present(GTK_WINDOW(plugin->popover));
        gtk_window_set_keep_above(GTK_WINDOW(plugin->popover), TRUE);
        gtk_image_set_from_icon_name(GTK_IMAGE(plugin->button_icon),
                                      "pan-up-symbolic", GTK_ICON_SIZE_BUTTON);
    }
    else
    {
        gtk_widget_hide(plugin->popover);
        gtk_image_set_from_icon_name(GTK_IMAGE(plugin->button_icon),
                                      "pan-down-symbolic", GTK_ICON_SIZE_BUTTON);
    }
}

/* Since we're using a plain GtkWindow instead of a GtkPopover, we lose
 * the automatic "close when focus leaves" behaviour popovers get for
 * free. This reimplements it: whenever the dropdown window loses
 * keyboard focus (the user clicked elsewhere, or switched windows),
 * hide it and reset the toggle button to match. */
static gboolean
on_dropdown_focus_out(GtkWidget *widget, GdkEventFocus *event, ExtrasMenuPlugin *plugin)
{
    (void) widget;
    (void) event;

    gtk_widget_hide(plugin->popover);
    gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(plugin->toggle_button), FALSE);
    gtk_image_set_from_icon_name(GTK_IMAGE(plugin->button_icon),
                                  "pan-down-symbolic", GTK_ICON_SIZE_BUTTON);

    return FALSE;
}

/* Called by the audio backend on connect and on every subsequent
 * volume/mute change, whether we caused it or something else did
 * (pavucontrol, media keys, ...). Updates the slider to match. */
static void
on_audio_changed(guint volume_percent, gboolean muted, gpointer user_data)
{
    ExtrasMenuPlugin *plugin = EXTRAS_MENU_PLUGIN(user_data);

    if (plugin->volume_scale == NULL)
        return;

    /* Setting the GtkRange's value below fires "value-changed" on the
     * slider; this flag tells our own handler (further down) that the
     * change originated from the backend, not from the user dragging
     * the slider, so it must not be echoed straight back to
     * PulseAudio -- that would just be a harmless but wasteful loop,
     * and could fight with the user's own drag in edge cases. */
    plugin->updating_volume_from_backend = TRUE;
    gtk_range_set_value(GTK_RANGE(plugin->volume_scale), (gdouble) volume_percent);
    plugin->updating_volume_from_backend = FALSE;

    /* Swap the speaker icon to its muted variant whenever the sink is
     * either explicitly muted or simply at 0% -- both look the same
     * to the user, so both get the crossed-out icon. Otherwise scale
     * the icon by level, matching what most desktop volume sliders do
     * (low/medium/high), purely as a visual nicety. */
    if (plugin->volume_icon != NULL)
    {
        const gchar *icon_name;

        if (muted || volume_percent == 0)
            icon_name = "audio-volume-muted-symbolic";
        else if (volume_percent < 34)
            icon_name = "audio-volume-low-symbolic";
        else if (volume_percent < 67)
            icon_name = "audio-volume-medium-symbolic";
        else
            icon_name = "audio-volume-high-symbolic";

        gtk_image_set_from_icon_name(GTK_IMAGE(plugin->volume_icon),
                                      icon_name, GTK_ICON_SIZE_BUTTON);
    }
}

/* Called when the user drags the slider (or otherwise changes its
 * value through the UI). Pushes the new value out to PulseAudio,
 * unless the change actually came from on_audio_changed() above. */
static void
on_volume_scale_changed(GtkRange *range, ExtrasMenuPlugin *plugin)
{
    if (plugin->updating_volume_from_backend)
        return;

    guint percent = (guint) gtk_range_get_value(range);
    extras_menu_audio_set_volume(plugin->audio, percent);
}

/* Same idea as on_audio_changed(), but for screen brightness via
 * brightnessctl. See brightness.h -- there's no live external-change
 * notification here (brightnessctl has no subscribe mechanism), so
 * this only fires on initial read and after our own set() calls. */
static void
on_brightness_changed(guint percent, gpointer user_data)
{
    ExtrasMenuPlugin *plugin = EXTRAS_MENU_PLUGIN(user_data);

    if (plugin->brightness_scale == NULL)
        return;

    plugin->updating_brightness_from_backend = TRUE;
    gtk_range_set_value(GTK_RANGE(plugin->brightness_scale), (gdouble) percent);
    plugin->updating_brightness_from_backend = FALSE;
}

/* Mirrors on_volume_scale_changed(), for the brightness slider. */
static void
on_brightness_scale_changed(GtkRange *range, ExtrasMenuPlugin *plugin)
{
    if (plugin->updating_brightness_from_backend)
        return;

    guint percent = (guint) gtk_range_get_value(range);
    extras_menu_brightness_set(plugin->brightness, percent);
}

/* Applies a Bluetooth state (available/powered) to the toggle widget.
 * Shared by on_bluetooth_changed() (the normal path) and the
 * end of construct() (to catch the case where the backend's first
 * callback arrived before the widget existed -- see
 * bluetooth_has_state in extras-menu.h for why that can happen). */
static void
apply_bluetooth_state(ExtrasMenuPlugin *plugin, gboolean available, gboolean powered)
{
    if (plugin->bluetooth_toggle == NULL)
        return;

    gtk_widget_set_sensitive(plugin->bluetooth_toggle, available);

    /* See on_audio_changed() for why this flag exists -- same
     * feedback-loop concern, this time against BlueZ. Explicitly force
     * the checked state to FALSE when unavailable (rather than leaving
     * whatever the button's initial/previous state was) -- a toggle
     * showing "on" while insensitive would be actively misleading. */
    plugin->updating_bluetooth_from_backend = TRUE;
    gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(plugin->bluetooth_toggle),
                                  available ? powered : FALSE);
    plugin->updating_bluetooth_from_backend = FALSE;
}

/* Called by the Bluetooth backend once we know the adapter's Powered
 * state, and again on every subsequent change (from us or elsewhere --
 * bluetoothctl, rfkill, a hardware switch). If no adapter is available
 * at all, the toggle is disabled outright rather than left in a
 * misleading on/off state.
 *
 * Always caches the latest state on the plugin first: GDBus has been
 * observed to invoke this callback before bluetooth_toggle has been
 * assigned yet in some cases (i.e. before extras_menu_bluetooth_new()
 * has returned to construct()), in which case apply_bluetooth_state()
 * below is a no-op and the state would otherwise be silently lost --
 * construct() re-applies the cached state once the widget exists. */
static void
on_bluetooth_changed(gboolean available, gboolean powered, gpointer user_data)
{
    ExtrasMenuPlugin *plugin = EXTRAS_MENU_PLUGIN(user_data);

    plugin->bluetooth_last_available = available;
    plugin->bluetooth_last_powered = powered;
    plugin->bluetooth_has_state = TRUE;

    apply_bluetooth_state(plugin, available, powered);
}

/* Called when the user clicks the Bluetooth pill. Pushes the new
 * power state out to BlueZ, unless the change actually came from
 * on_bluetooth_changed() above. */
static void
on_bluetooth_toggle_clicked(GtkToggleButton *button, ExtrasMenuPlugin *plugin)
{
    if (plugin->updating_bluetooth_from_backend)
        return;

    extras_menu_bluetooth_set_powered(plugin->bluetooth,
                                       gtk_toggle_button_get_active(button));
}

/* Fired when the user picks "Properties..." from the plugin's
 * right-click panel menu (enabled via
 * xfce_panel_plugin_menu_show_configure() in construct() below). */
static void
on_plugin_configure(XfcePanelPlugin *panel_plugin, ExtrasMenuPlugin *plugin)
{
    (void) plugin;
    extras_menu_preferences_show(panel_plugin);
}

static void
on_plugin_free_data(XfcePanelPlugin *panel_plugin, ExtrasMenuPlugin *plugin)
{
    (void) panel_plugin;

    if (plugin->audio != NULL)
    {
        extras_menu_audio_free(plugin->audio);
        plugin->audio = NULL;
    }

    if (plugin->brightness != NULL)
    {
        extras_menu_brightness_free(plugin->brightness);
        plugin->brightness = NULL;
    }

    if (plugin->bluetooth != NULL)
    {
        extras_menu_bluetooth_free(plugin->bluetooth);
        plugin->bluetooth = NULL;
    }
}

static void
extras_menu_plugin_construct(XfcePanelPlugin *panel_plugin)
{
    ExtrasMenuPlugin *plugin = EXTRAS_MENU_PLUGIN(panel_plugin);

    /* --- panel button (the "^" chevron trigger) --- */
    plugin->toggle_button = gtk_toggle_button_new();
    gtk_button_set_relief(GTK_BUTTON(plugin->toggle_button), GTK_RELIEF_NONE);

    plugin->button_icon = gtk_image_new_from_icon_name("pan-down-symbolic",
                                                         GTK_ICON_SIZE_BUTTON);
    gtk_container_add(GTK_CONTAINER(plugin->toggle_button), plugin->button_icon);

    gtk_container_add(GTK_CONTAINER(panel_plugin), plugin->toggle_button);
    xfce_panel_plugin_add_action_widget(panel_plugin, plugin->toggle_button);

    /* --- dropdown window, built once and reused on every open ---
     * GTK_WINDOW_POPUP gives us an undecorated, non-taskbar window
     * (no titlebar, no border) similar in spirit to a popover, but as
     * a real top-level window we fully control the position and
     * stacking of -- see extras-menu.h for why we moved away from
     * GtkPopover. */
    plugin->popover = gtk_window_new(GTK_WINDOW_POPUP);
    gtk_window_set_type_hint(GTK_WINDOW(plugin->popover), GDK_WINDOW_TYPE_HINT_POPUP_MENU);
    gtk_window_set_decorated(GTK_WINDOW(plugin->popover), FALSE);
    gtk_window_set_skip_taskbar_hint(GTK_WINDOW(plugin->popover), TRUE);
    gtk_window_set_skip_pager_hint(GTK_WINDOW(plugin->popover), TRUE);
    gtk_window_set_resizable(GTK_WINDOW(plugin->popover), FALSE);

    GtkWidget *content = extras_menu_popover_content_new(&plugin->volume_scale,
                                                           &plugin->volume_icon,
                                                           &plugin->brightness_scale,
                                                           &plugin->bluetooth_toggle);
    gtk_container_add(GTK_CONTAINER(plugin->popover), content);

    /* Frame + drop shadow so the window doesn't look like a bare
     * rectangle floating over the desktop -- GtkPopover normally gives
     * us this via its own CSS node, which we no longer have. */
    {
        GtkStyleContext *ctx = gtk_widget_get_style_context(plugin->popover);
        gtk_style_context_add_class(ctx, "background");

        GtkCssProvider *frame_provider = gtk_css_provider_new();
        gtk_css_provider_load_from_data(
            frame_provider,
            "window { "
            "  border-radius: 12px; "
            "  box-shadow: 0 4px 16px rgba(0, 0, 0, 0.35); "
            "}",
            -1, NULL);
        gtk_style_context_add_provider(ctx, GTK_STYLE_PROVIDER(frame_provider),
                                        GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);
        g_object_unref(frame_provider);
    }

    g_signal_connect(plugin->toggle_button, "clicked",
                      G_CALLBACK(on_toggle_button_clicked), plugin);
    g_signal_connect(plugin->popover, "focus-out-event",
                      G_CALLBACK(on_dropdown_focus_out), plugin);

    /* --- audio backend: connects asynchronously, reports state (and
     * every subsequent change) through on_audio_changed --- */
    plugin->audio = extras_menu_audio_new(on_audio_changed, plugin);

    if (plugin->volume_scale != NULL)
    {
        g_signal_connect(plugin->volume_scale, "value-changed",
                          G_CALLBACK(on_volume_scale_changed), plugin);
    }

    /* --- brightness backend: reads the current value async on start,
     * reports it (and every value we set afterwards) through
     * on_brightness_changed --- */
    plugin->brightness = extras_menu_brightness_new(on_brightness_changed, plugin);

    if (plugin->brightness_scale != NULL)
    {
        g_signal_connect(plugin->brightness_scale, "value-changed",
                          G_CALLBACK(on_brightness_scale_changed), plugin);
    }

    /* --- Bluetooth backend: finds the first adapter async, reports
     * its Powered state (and every subsequent change) through
     * on_bluetooth_changed. Device list / pairing is a follow-up --
     * for now this only drives the adapter on/off toggle. --- */
    plugin->bluetooth = extras_menu_bluetooth_new(on_bluetooth_changed, plugin);

    if (plugin->bluetooth_toggle != NULL)
    {
        /* Disabled until the backend confirms an adapter actually
         * exists (see on_bluetooth_changed) -- avoids a toggle that
         * looks clickable but silently does nothing on machines
         * without Bluetooth hardware. */
        gtk_widget_set_sensitive(plugin->bluetooth_toggle, FALSE);
        g_signal_connect(plugin->bluetooth_toggle, "toggled",
                          G_CALLBACK(on_bluetooth_toggle_clicked), plugin);

        /* Catch up on any state the backend already reported before
         * this widget existed -- see bluetooth_has_state in
         * extras-menu.h for why that can happen. */
        if (plugin->bluetooth_has_state)
        {
            apply_bluetooth_state(plugin, plugin->bluetooth_last_available,
                                   plugin->bluetooth_last_powered);
        }
    }

    g_signal_connect(panel_plugin, "free-data",
                      G_CALLBACK(on_plugin_free_data), plugin);

    /* --- "Properties..." entry in the plugin's right-click panel menu,
     * opening the (currently minimal) preferences dialog --- */
    xfce_panel_plugin_menu_show_configure(panel_plugin);
    g_signal_connect(panel_plugin, "configure-plugin",
                      G_CALLBACK(on_plugin_configure), plugin);

    gtk_widget_show_all(plugin->toggle_button);
}